### ISSUE TITLE
Packaging as Flatpak

### ISSUE THREAD

**Issue by Kentoseth** [C-Loftus/Starling#2]
This looks like an amazing tool that I can use to replace my keyboard/mouse for much navigation.

However, it has system dependencies that will make it hard to use across distros.

Can you possibly package this as a Flatpak app?

As an aside Q: is this the only Linux voice-based desktop control software out there? The rest all seem like home assistant tools.

**Comment by C-Loftus** [comment]
Hi there,

This tool was mainly developed for academic/hci research purposes. For health reasons, I unfortunately don't really have the bandwidth to figure out packaging this.

I highly suggest you try out Talon Voice which is currently the best option on Linux or any other platform for that matter. The website for the project is [https://talonvoice.com/](https://talonvoice.com/). Then you have to install scripts which come from
[https://github.com/talonhub/community](https://github.com/talonhub/community). That is the repo for the community scripts  and has other good resources for learning Talon.

Once you get familiar with Talon, I have a lot of other Talon scripts on my GitHub profile that may perhaps be of interest. If you want individual help, feel free to reach out to my on my website
